# =============================================================================
# NOTIFY-STACK - Email Providers Configuration
# =============================================================================
# Configuración de proveedores de email (SMTP y API)
# Las credenciales sensibles se obtienen de variables de entorno

# =============================================================================
# DEVELOPMENT PROVIDERS
# =============================================================================

# MailPit - Proveedor principal para desarrollo
mailpit:
  type: "smtp"
  name: "MailPit Development"
  description: "Capturador de correos para desarrollo y testing"
  
  # Configuración de conexión
  host: "mailpit"
  port: 1025
  username: ""
  password: ""
  
  # Configuración de seguridad (sin TLS en desarrollo)
  use_tls: false
  use_ssl: false
  verify_certificate: false
  
  # Configuración de headers
  from_email: "dev@notify-system.local"
  from_name: "Notify Dev System"
  reply_to: "dev@notify-system.local"
  return_path: "dev@notify-system.local"
  
  # Límites y timeouts
  timeout: 15
  max_recipients_per_message: 100
  max_messages_per_hour: 1000
  max_attachment_size: 25165824  # 24MB
  
  # Configuración operacional
  priority: "high"
  category: "development"
  enabled: true
  
  # Características soportadas
  features:
    html_support: true
    attachments: true
    tracking: false
    analytics: false
    templates: false
    
  # Configuración de reintentos
  retry:
    max_attempts: 1  # Sin reintentos en desarrollo
    backoff_factor: 1
    initial_delay: 0

# =============================================================================
# SMTP PROVIDERS
# =============================================================================

# Proveedor SMTP principal (Gmail)
smtp_primary:
  type: "smtp"
  name: "Gmail SMTP Primary"
  description: "Proveedor principal para emails transaccionales"
  
  # Configuración de conexión
  host: "${SMTP_GMAIL_HOST}"
  port: "${SMTP_GMAIL_PORT}"
  username: "${SMTP_GMAIL_USERNAME}"
  password: "${SMTP_GMAIL_PASSWORD}"
  
  # Configuración de seguridad
  use_tls: true
  use_ssl: false
  verify_certificate: true
  
  # Configuración de headers
  from_email: "${SMTP_GMAIL_USERNAME}"
  from_name: "${SMTP_GMAIL_FROM_NAME}"
  reply_to: "${SMTP_GMAIL_USERNAME}"
  return_path: "${SMTP_GMAIL_USERNAME}"
  
  # Límites y timeouts
  timeout: 30
  max_recipients_per_message: 100
  max_messages_per_hour: 500
  max_attachment_size: 25165824  # 24MB (Gmail limit)
  
  # Configuración operacional
  priority: "high"
  category: "transactional"
  enabled: true  # Disabled en desarrollo
  
  # Características soportadas
  features:
    html_support: true
    attachments: true
    tracking: false
    analytics: false
    templates: false
    
  # Configuración de reintentos
  retry:
    max_attempts: 3
    backoff_factor: 2
    initial_delay: 60

# Proveedor SMTP secundario (Outlook)
smtp_secondary:
  type: "smtp"
  name: "Outlook SMTP Secondary"
  description: "Proveedor de respaldo para failover"
  
  host: "${SMTP_OUTLOOK_HOST}"
  port: "${SMTP_OUTLOOK_PORT}"
  username: "${SMTP_OUTLOOK_USERNAME}"
  password: "${SMTP_OUTLOOK_PASSWORD}"
  
  use_tls: true
  use_ssl: false
  
  from_email: "${SMTP_OUTLOOK_USERNAME}"
  from_name: "Notify System Backup"
  
  timeout: 30
  max_recipients_per_message: 50
  max_messages_per_hour: 300
  
  priority: "medium"
  category: "backup"
  enabled: true  # Disabled en desarrollo
  
  features:
    html_support: true
    attachments: true
    tracking: false

# Proveedor SMTP para bulk/marketing
smtp_bulk:
  type: "smtp"
  name: "Custom SMTP Bulk"
  description: "Proveedor optimizado para envíos masivos"
  
  host: "${SMTP_CUSTOM_HOST}"
  port: "${SMTP_CUSTOM_PORT}"
  username: "${SMTP_CUSTOM_USERNAME}"
  password: "${SMTP_CUSTOM_PASSWORD}"
  
  use_tls: true
  use_ssl: false
  
  from_email: "${SMTP_CUSTOM_USERNAME}"
  from_name: "Newsletter System"
  
  timeout: 45
  max_recipients_per_message: 500
  max_messages_per_hour: 2000
  
  priority: "medium"
  category: "bulk"
  enabled: true  # Disabled en desarrollo
  
  features:
    html_support: true
    attachments: false  # No attachments en bulk
    tracking: false

# Proveedor SMTP para testing
smtp_test:
  type: "smtp"
  name: "Test SMTP Provider"
  description: "Proveedor exclusivo para testing y desarrollo"
  
  host: "smtp.mailtrap.io"  # Servicio de testing
  port: 587
  username: "${SMTP_TEST_USERNAME}"
  password: "${SMTP_TEST_PASSWORD}"
  
  use_tls: true
  use_ssl: false
  
  from_email: "test@notify-system.local"
  from_name: "Notify Test System"
  
  timeout: 15
  max_recipients_per_message: 10
  max_messages_per_hour: 100
  
  priority: "low"
  category: "testing"
  enabled: true  # Usar MailPit en su lugar
  
  features:
    html_support: true
    attachments: true
    tracking: true    # Mailtrap soporta tracking

# =============================================================================
# API PROVIDERS
# =============================================================================

# SendGrid API
api_sendgrid:
  type: "api"
  provider_type: "sendgrid"
  name: "SendGrid API"
  description: "Proveedor API premium con tracking avanzado"
  
  # Configuración de API
  endpoint: "https://api.sendgrid.com"
  api_key: "${SENDGRID_API_KEY}"
  
  # Configuración de headers
  from_email: "${SENDGRID_FROM_EMAIL}"
  from_name: "${SENDGRID_FROM_NAME}"
  reply_to: "${SENDGRID_FROM_EMAIL}"
  
  # Límites API
  timeout: 30
  max_recipients_per_message: 1000
  max_messages_per_hour: 10000
  max_attachment_size: 10485760  # 10MB
  
  # Configuración operacional
  priority: "high"
  category: "premium"
  enabled: true  # Disabled en desarrollo
  
  # Características avanzadas
  features:
    html_support: true
    attachments: true
    tracking: true
    analytics: true
    templates: true
    webhooks: true
    
  # Configuración específica de SendGrid
  sendgrid:
    # Tracking settings
    tracking:
      click_tracking: true
      open_tracking: true
      subscription_tracking: false
      
    # Configuración de templates
    template_engine: true
    dynamic_templates: true
    
    # Configuración de IP
    ip_pool_name: "default"
    
  retry:
    max_attempts: 3
    backoff_factor: 1.5
    initial_delay: 30

# Amazon SES API
api_ses:
  type: "api"
  provider_type: "ses"
  name: "Amazon SES"
  description: "Proveedor AWS altamente escalable"
  
  endpoint: "https://email.${AWS_SES_REGION}.amazonaws.com"
  api_key: "${AWS_SES_ACCESS_KEY_ID}"
  secret_key: "${AWS_SES_SECRET_ACCESS_KEY}"
  region: "${AWS_SES_REGION}"
  
  from_email: "${AWS_SES_FROM_EMAIL}"
  from_name: "AWS Notifications"
  
  timeout: 30
  max_recipients_per_message: 50
  max_messages_per_hour: 14000  # SES limit in sandbox
  
  priority: "high"
  category: "scalable"
  enabled: true  # Disabled by default
  
  features:
    html_support: true
    attachments: true
    tracking: true
    analytics: true
    templates: true
    
  # Configuración específica de SES
  ses:
    configuration_set: "default"
    
  retry:
    max_attempts: 3
    backoff_factor: 2
    initial_delay: 45

# Mailgun API
api_mailgun:
  type: "api"
  provider_type: "mailgun"
  name: "Mailgun API"
  description: "Proveedor API con excelente deliverability"
  
  endpoint: "https://api.mailgun.net/v3/${MAILGUN_DOMAIN}"
  api_key: "${MAILGUN_API_KEY}"
  domain: "${MAILGUN_DOMAIN}"
  
  from_email: "${MAILGUN_FROM_EMAIL}"
  from_name: "Mailgun Notifications"
  
  timeout: 30
  max_recipients_per_message: 1000
  max_messages_per_hour: 5000
  
  priority: "medium"
  category: "marketing"
  enabled: true
  
  features:
    html_support: true
    attachments: true
    tracking: true
    analytics: true
    
  retry:
    max_attempts: 3
    backoff_factor: 2
    initial_delay: 30

# Proveedor API genérico (para futuras integraciones)
api_generic:
  type: "api"
  provider_type: "generic"
  name: "Generic API Provider"
  description: "Proveedor API genérico configurable"
  
  endpoint: "${GENERIC_API_ENDPOINT}"
  api_key: "${GENERIC_API_KEY}"
  
  from_email: "${GENERIC_FROM_EMAIL}"
  from_name: "Generic Provider"
  
  timeout: 30
  max_recipients_per_message: 100
  max_messages_per_hour: 1000
  
  priority: "low"
  category: "experimental"
  enabled: true
  
  # Headers personalizados
  headers:
    "User-Agent": "NotifyAPI/1.0"
    "X-Custom-Header": "notify-stack"
    
  features:
    html_support: true
    attachments: false
    
  retry:
    max_attempts: 2
    backoff_factor: 1
    initial_delay: 60

# =============================================================================
# TWILIO PROVIDERS - ACTUALIZACIONES SEGURAS
# =============================================================================

# Twilio SMS - Configuración mejorada pero conservadora
twilio_sms:
  type: "twilio"
  provider_type: "twilio_sms"
  name: "Twilio SMS"
  description: "Proveedor SMS via Twilio API"
  
  # Configuración de API
  account_sid: "${TWILIO_ACCOUNT_SID}"
  auth_token: "${TWILIO_AUTH_TOKEN}"
  from_number: "${TWILIO_SMS_FROM}"
  
  # Límites SMS conservadores
  timeout: 30
  max_recipients_per_message: 10  # Límite conservador para no sobrecargar
  max_message_length: 1600
  max_messages_per_hour: 100      # Límite conservador inicialmente
  
  # Configuración operacional
  priority: "high"
  category: "sms"
  enabled: true  # DISABLED por defecto para no romper nada
  
  # Características soportadas
  features:
    html_support: false
    attachments: false
    tracking: true
    delivery_reports: true
    status_callbacks: true
    
  # Configuración específica SMS
  sms_config:
    # Webhook URL para status callbacks
    webhook_url: "${TWILIO_SMS_WEBHOOK_URL}"
    
    # Configuración de entrega
    validity_period: 86400  # 24 horas
    
    # Configuración de encoding
    encoding: "UTF-8"
    smart_encoding: true
    
  # Configuración de reintentos
  retry:
    max_attempts: 2  # Menos reintentos para SMS
    backoff_factor: 1.5
    initial_delay: 30

# Twilio WhatsApp - Configuración mejorada pero conservadora  
twilio_whatsapp:
  type: "twilio"
  provider_type: "twilio_whatsapp"
  name: "Twilio WhatsApp"
  description: "Proveedor WhatsApp Business via Twilio API"
  
  # Configuración de API
  account_sid: "${TWILIO_ACCOUNT_SID}"
  auth_token: "${TWILIO_AUTH_TOKEN}"
  from_number: "${TWILIO_WHATSAPP_FROM}"  # Formato: whatsapp:+14155238886
  
  # Límites WhatsApp conservadores
  timeout: 45
  max_recipients_per_message: 5   # Muy conservador para WhatsApp
  max_message_length: 4096
  max_media_count: 5              # Límite conservador de medios
  max_media_size: 16777216        # 16MB
  max_messages_per_hour: 50       # Límite muy conservador
  
  # Configuración operacional
  priority: "high"
  category: "whatsapp"
  enabled: true  # DISABLED por defecto para no romper nada
  
  # Características soportadas
  features:
    html_support: false
    attachments: true
    media_support: true
    tracking: true
    delivery_reports: true
    read_receipts: true
    templates: true               # WhatsApp Business Templates
    
  # Tipos de media soportados (lista conservadora)
  supported_media_types:
    - "image/jpeg"
    - "image/png" 
    - "application/pdf"
    - "text/plain"
    
  # Configuración específica WhatsApp
  whatsapp_config:
    # Webhook URL para status callbacks
    webhook_url: "${TWILIO_WHATSAPP_WEBHOOK_URL}"
    
    # Configuración de templates
    use_templates: true
    fallback_language: "en"
    
    # Configuración de medios
    media_upload_timeout: 60
    
  # Configuración de reintentos
  retry:
    max_attempts: 2  # Menos reintentos para WhatsApp
    backoff_factor: 2
    initial_delay: 60

# =============================================================================
# PROVIDER GROUPS & LOAD BALANCING - ACTUALIZACIÓN CONSERVADORA
# =============================================================================

# Grupos de proveedores para load balancing
provider_groups:
  # Grupo principal para desarrollo (SIN CAMBIOS)
  development:
    providers:
      - name: "mailpit"
        weight: 100
    load_balancing: "single"
    health_check: false
    
  # Grupo principal para emails transaccionales (SIN CAMBIOS)
  transactional:
    providers:
      - name: "smtp_primary"
        weight: 70
      - name: "api_sendgrid"
        weight: 30
    load_balancing: "weighted_round_robin"
    health_check: true
    
  # Grupo para envíos masivos (SIN CAMBIOS)
  bulk:
    providers:
      - name: "smtp_bulk"
        weight: 60
      - name: "api_mailgun"
        weight: 40
    load_balancing: "round_robin"
    health_check: true
    
  # Grupo de backup/failover (SIN CAMBIOS)
  backup:
    providers:
      - name: "smtp_secondary"
        weight: 50
      - name: "api_ses"
        weight: 50
    load_balancing: "failover"
    health_check: true
    
  # NUEVO: Grupo para SMS (opcional, deshabilitado por defecto)
  sms:
    providers:
      - name: "twilio_sms"
        weight: 100
    load_balancing: "single"
    health_check: true
    enabled: true  # Disabled por defecto
    
  # NUEVO: Grupo para WhatsApp (opcional, deshabilitado por defecto)  
  whatsapp:
    providers:
      - name: "twilio_whatsapp"
        weight: 100
    load_balancing: "single"
    health_check: true
    enabled: true  # Disabled por defecto

# =============================================================================
# HEALTH MONITORING - ACTUALIZACIÓN SEGURA
# =============================================================================

# Configuración de monitoreo de salud
health_monitoring:
  # Intervalos de verificación (SIN CAMBIOS)
  check_intervals:
    fast_check: 60      # segundos
    full_check: 300     # segundos
    
  # Criterios de salud (SIN CAMBIOS)
  health_criteria:
    max_response_time: 5.0      # segundos
    max_error_rate: 5.0         # porcentaje
    min_success_rate: 95.0      # porcentaje
    
  # Criterios específicos para SMS/WhatsApp (NUEVO)
  sms_health_criteria:
    max_response_time: 10.0     # SMS puede ser más lento
    max_error_rate: 10.0        # Más tolerante a errores
    min_success_rate: 90.0      # Estándar más bajo
    
  whatsapp_health_criteria:
    max_response_time: 15.0     # WhatsApp puede ser más lento
    max_error_rate: 15.0        # Más tolerante a errores  
    min_success_rate: 85.0      # Estándar más bajo
    
  # Acciones automáticas (SIN CAMBIOS)
  auto_actions:
    disable_unhealthy: true
    alert_on_failure: true
    
  # Configuración de alertas (SIN CAMBIOS)
  alerts:
    webhook_url: "${ALERT_WEBHOOK_URL}"
    email_alerts: ["admin@yourcompany.com"]

# =============================================================================
# COST OPTIMIZATION - ACTUALIZACIÓN CONSERVADORA  
# =============================================================================

# Configuración de optimización de costos
cost_optimization:
  # Routing por costo (SIN CAMBIOS)
  cost_aware_routing: true
  
  # Costos relativos por proveedor (ACTUALIZADO con SMS/WhatsApp)
  provider_costs:
    mailpit: 0          # Gratis en desarrollo
    smtp_primary: 2
    smtp_secondary: 2
    smtp_bulk: 1
    api_sendgrid: 4
    api_ses: 3
    api_mailgun: 4
    twilio_sms: 8       # SMS tiene costo por mensaje (más alto)
    twilio_whatsapp: 10 # WhatsApp más caro que SMS (más alto)
    
  # Límites de costo (CONSERVADORES para incluir SMS/WhatsApp)
  cost_limits:
    max_daily_cost: 50.0        # USD - Límite más bajo para ser conservador
    alert_threshold: 30.0       # USD - Alerta temprana
    
  # Optimizaciones automáticas (SIN CAMBIOS)
  auto_optimizations:
    prefer_cheaper_for_bulk: true
    route_off_hours_to_cheaper: true

# =============================================================================
# COMPLIANCE & REGION SETTINGS (SIN CAMBIOS)
# =============================================================================

# Configuración por región geográfica
regional_settings:
  # Estados Unidos
  us:
    preferred_providers: ["api_sendgrid", "smtp_primary"]
    compliance_requirements: ["can_spam"]
    
  # Unión Europea  
  eu:
    preferred_providers: ["api_mailgun", "smtp_secondary"]
    compliance_requirements: ["gdpr"]
    data_residency: "eu"
    
  # Asia-Pacífico
  apac:
    preferred_providers: ["api_ses", "smtp_primary"]
    compliance_requirements: ["local_privacy_laws"]

# =============================================================================
# DEVELOPMENT & TESTING - ACTUALIZACIÓN CONSERVADORA
# =============================================================================

# Configuración para desarrollo
development:
  # Proveedor por defecto en desarrollo (SIN CAMBIOS)
  default_provider: "mailpit"
  
  # Interceptar emails en desarrollo (SIN CAMBIOS)
  email_interception:
    enabled: true  # MailPit ya intercepta todo
    redirect_to: ["dev@yourcompany.com"]
    
  # NUEVO: Configuración para SMS/WhatsApp en desarrollo
  sms_testing:
    mock_enabled: true          # Mock SMS en desarrollo
    test_numbers: ["+1234567890"] # Números de prueba
    
  whatsapp_testing:
    mock_enabled: true          # Mock WhatsApp en desarrollo
    test_numbers: ["whatsapp:+1234567890"] # Números de prueba
    
  # Simulación de fallos para testing (SIN CAMBIOS)
  failure_simulation:
    enabled: true
    failure_rate: 0.1  # 10% de fallos simulados
    
  # Logging detallado (SIN CAMBIOS)
  debug_logging: true

# =============================================================================
# PROVIDER STATISTICS - ACTUALIZACIÓN SEGURA
# =============================================================================

# Métricas y estadísticas
statistics:
  # Métricas a trackear (ACTUALIZADO con SMS/WhatsApp)
  tracked_metrics:
    - "messages_sent"
    - "messages_failed"
    - "response_time"
    - "cost_per_message"
    - "delivery_rate"
    - "sms_segments"      # NUEVO: Segmentos SMS
    - "whatsapp_reads"    # NUEVO: Lecturas WhatsApp
    
  # Retención de métricas (SIN CAMBIOS)
  retention:
    hourly_data: 48     # horas
    daily_data: 90      # días
    monthly_data: 24    # meses
    
  # Alertas basadas en métricas (ACTUALIZADO)
  metric_alerts:
    high_failure_rate:
      threshold: 10.0   # porcentaje
      window: 300       # segundos
    slow_response:
      threshold: 10.0   # segundos  
      window: 600       # segundos
    high_sms_cost:      # NUEVO
      threshold: 20.0   # USD por hora
      window: 3600      # 1 hora